spring:
  application:
    name: pdv
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enable: true
      path: /h2-console
pdv:
  default:
    price-table: Padrão
    payment-methods:
      - Cartão de crédito
      - Cartão de débito
      - Dinheiro
      - Pix
      - Outros